name: Build and Testing
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_FEED_NAME: github
      NUGET_FEED_USERNAME: dns177
      NUGET_FEED_URL: https://nuget.pkg.github.com/dns177/index.json
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      # - name: Configure Nuget feed
      #   run: dotnet nuget add source ${{ env.NUGET_FEED_URL }} -n ${{ env.NUGET_FEED_NAME }} -u ${{ env.NUGET_FEED_USERNAME }} -p ${{ secrets.GITHUBPACKAGESECRETS }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal
