name: "Build, Testing and Deploy to Cloud Run"

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: "repicach"
  GAR_NAME: "gh-wallet"
  GCP_REGION: "us-central1"
  SERVICE: "wallet-api"

jobs:
  # Build and Testing
  build:
    uses: ./.github/workflows/dotnet.yml

  # Deploy to Google Cloud Run
  deploy-to-cloudrun:
    runs-on: "ubuntu-latest"
    needs: build

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      # Authentication Docker to Google Cloud Artifact Registry
      - name: "Docker Auth"
        run: |-
          gcloud auth configure-docker "${{ env.GCP_REGION }}-docker.pkg.dev"

      - name: "Build and Push Container"
        run: |-
          DOCKER_TAG="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build -t "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"
      # END - Docker auth and build
      
      - name: "Deploy to Cloud Run"
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          project_id: "${{env.PROJECT_ID}}"
          service: "${{ env.SERVICE }}"
          region: "${{ env.GCP_REGION }}"

          # NOTE: If using a pre-built image, update the image name below:
          image: "${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"

      # If required, use the Cloud Run URL output in later steps
      - name: "Show output"
        run: |-
          echo ${{ steps.deploy.outputs.url }}
